// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe3Be6hil992Y3KKEfDB5UKRnPFhkfHD4',
    appId: '1:337941394841:web:e91a9d7aa07bfeb9828f08',
    messagingSenderId: '337941394841',
    projectId: 'booksy-532e0',
    authDomain: 'booksy-532e0.firebaseapp.com',
    storageBucket: 'booksy-532e0.appspot.com',
    measurementId: 'G-725X5770BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6x-auoHAwL8xw4WPFdlQKKKgaB0ZsL94',
    appId: '1:337941394841:android:03be75401b02d399828f08',
    messagingSenderId: '337941394841',
    projectId: 'booksy-532e0',
    storageBucket: 'booksy-532e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByTQedlTYnJ8NXPd-FKiq9wCipf8YiRh4',
    appId: '1:337941394841:ios:39fa8b4d438b6028828f08',
    messagingSenderId: '337941394841',
    projectId: 'booksy-532e0',
    storageBucket: 'booksy-532e0.appspot.com',
    iosBundleId: 'com.example.booksyAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByTQedlTYnJ8NXPd-FKiq9wCipf8YiRh4',
    appId: '1:337941394841:ios:a2ec221696017b71828f08',
    messagingSenderId: '337941394841',
    projectId: 'booksy-532e0',
    storageBucket: 'booksy-532e0.appspot.com',
    iosBundleId: 'com.example.booksyAdmin.RunnerTests',
  );
}
